services:
  # nest-app:
  #   build:
  #     context: ./
  #     dockerfile: ./Dockerfile
  #   depends_on:
  #     - mysql-container
  #     - redis-container
  #   ports:
  #     - '3000:3000'

  mysql:
    container_name: mysql
    image: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: temple
      MYSQL_ROOT_PASSWORD: wo123456

  # redis-container:
  #   image: redis
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - /Users/guang/aaa:/data
